config/routes.rb
Rails.application.routes.draw do
  resources :products

  
  get 'inicio/index'

  root 'inicio#index'
  
  resources :marca_proveedors
  get 'proveedor_marca/index'

  get 'proveedor_marca/show'

  get 'proveedor_marca/create'

  resources :sub_categories
  resources :categories
  resources :marcas
  resources :proveedores
  resources :sucursals

end

app/models/marca.rb
class Marca < ActiveRecord::Base
	has_many :MarcaProveedor
	has_many :Product

	
	
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :set_marca, only: [:show, :edit, :update, :destroy]

  # GET /marcas
  # GET /marcas.json
  def index
    @marcas = Marca.all
    @prov = Proveedore.all
    @marca_proveedor = MarcaProveedor.all
  end
  # GET /marcas/1
  # GET /marcas/1.json
  def show
  end

  # GET /marcas/new
  def new
    @marca = Marca.new
  end

  # GET /marcas/1/edit
  def edit
  end

  # POST /marcas
  # POST /marcas.json
  def create
    @marca = Marca.new(marca_params)

    respond_to do |format|
      if @marca.save
        format.html { redirect_to @marca, notice: 'Marca was successfully created.' }
        format.json { render :show, status: :created, location: @marca }
      else
        format.html { render :new }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marcas/1
  # PATCH/PUT /marcas/1.json
  def update
    respond_to do |format|
      if @marca.update(marca_params)
        format.html { redirect_to @marca, notice: 'Marca was successfully updated.' }
        format.json { render :show, status: :ok, location: @marca }
      else
        format.html { render :edit }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    @marca.destroy
    respond_to do |format|
      format.html { redirect_to marcas_url, notice: 'Marca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marca_params
      params.require(:marca).permit(:descrip)
    end
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/views/marcas/_form.html.erb
<%= form_for(@marca) do |f| %>
  <% if @marca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marca.errors.count, "error") %> prohibited this marca from being saved:</h2>

      <ul>
      <% @marca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descrip %><br>
    <%= f.text_field :descrip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/marcas/edit.html.erb
<h1>Editing Marca</h1>

<%= render 'form' %>

<%= link_to 'Show', @marca %> |
<%= link_to 'Back', marcas_path %>

app/views/marcas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marcas</h1>



<table class="table table-stripped">
  <thead>
    <tr align="left">
      <th >Descripcion</th>
      <th colspan="4" >Opciones</th>
     
    </tr>
  </thead>

  <tbody>
    <% @marcas.each do |marca| %>
      <tr>
        <td><%= marca.descrip %></td>
        <td> <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#myModal">Agregar proveedor</button></td>
        <td><%= link_to 'Show', marca %></td>
        <td><%= link_to 'Edit', edit_marca_path(marca) %></td>
        <td><%= link_to 'Destroy', marca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><font color="black">Marcas por proveedores</font></h4>
        </div>
        <div class="modal-body">
<h1><font color="black">Proveedores</font></h1>


<%= render  'marca_proveedors/tabla' %>


    
</div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
</div>




<%= link_to 'New Marca', new_marca_path %>

app/views/marcas/new.html.erb
<h1>New Marca</h1>

<%= render 'form' %>

<%= link_to 'Back', marcas_path %>

app/views/marcas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrip:</strong>
  <%= @marca.descrip %>
</p>

<%= link_to 'Edit', edit_marca_path(@marca) %> |
<%= link_to 'Back', marcas_path %>