config/routes.rb
Rails.application.routes.draw do
  resources :products

  
  get 'inicio/index'

  root 'inicio#index'
  
  resources :marca_proveedors
  get 'proveedor_marca/index'

  get 'proveedor_marca/show'

  get 'proveedor_marca/create'

  resources :sub_categories
  resources :categories
  resources :marcas
  resources :proveedores
  resources :sucursals

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :Category
  has_many :Product
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.all
    @category = Category.all
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
    @category = Category.all
    #.map { |c| [ c.descripcion, c.id ] }
  end

  # GET /sub_categories/1/edit
  def edit
    @category = Category.all
    #.map { |c| [ c.descripcion, c.id ] }
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)
    @category = Category.all
    #.map { |c| [ c.descripcion, c.id ] }
    puts params

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    @category = Category.all
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_params
      params.require(:sub_category).permit(:descripcion, :category_id)
    end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<%= form_for(@sub_category) do |f| %>
  <% if @sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
      <% @sub_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    
    
<%= select_tag("sub_category[category_id]",  options_for_select(@category.map{|c|["#{c.descripcion}", c.id]})) %>
   

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
          $(document).ready(function() {
            console.log("hola")
          $('select#sub_category_category_id').select2({
            placeholder: "Categoria",
            allowClear: true
          });
        });
</script>

app/views/sub_categories/edit.html.erb
<h1>Editing Sub Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sub Categories</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.descripcion %></td>
        <td><%= sub_category.category.descripcion %></td>
        <td><span class="glyphicon glyphicon-eye-open"><%= link_to '   Mostrar', sub_category %></span></td>
        <td><span class="glyphicon glyphicon-pencil"><%= link_to '   Editar', edit_sub_category_path(sub_category) %></span></td>
        <td><span class="glyphicon glyphicon-trash"><%= link_to '   Eliminar', sub_category, method: :delete, data: { confirm: 'Esta seguro?' } %></span></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub category', new_sub_category_path %>

app/views/sub_categories/new.html.erb
<h1>New Sub Category</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @sub_category.descripcion %>
</p>

<p>
  <strong>Category:</strong>
  <%= @sub_category.category.descripcion %>
</p>

<%= link_to 'Edit', edit_sub_category_path(@sub_category) %> |
<%= link_to 'Back', sub_categories_path %>