config/routes.rb
Rails.application.routes.draw do
  resources :products

  
  get 'inicio/index'

  root 'inicio#index'
  
  resources :marca_proveedors
  get 'proveedor_marca/index'

  get 'proveedor_marca/show'

  get 'proveedor_marca/create'

  resources :sub_categories
  resources :categories
  resources :marcas
  resources :proveedores
  resources :sucursals

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :SubCategory
end

app/models/marca.rb
class Marca < ActiveRecord::Base
	has_many :MarcaProveedor
	has_many :Product

	
	
end

app/models/marca_proveedor.rb
class MarcaProveedor < ActiveRecord::Base
  belongs_to :marca
  belongs_to :proveedore
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :Sub_category
  belongs_to :Marca
end

app/models/proveedore.rb
class Proveedore < ActiveRecord::Base
	has_many :MarcaProveedor
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :Category
  has_many :Product
end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  	
  end
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :set_marca, only: [:show, :edit, :update, :destroy]

  # GET /marcas
  # GET /marcas.json
  def index
    @marcas = Marca.all
    @prov = Proveedore.all
    @marca_proveedor = MarcaProveedor.all
  end
  # GET /marcas/1
  # GET /marcas/1.json
  def show
  end

  # GET /marcas/new
  def new
    @marca = Marca.new
  end

  # GET /marcas/1/edit
  def edit
  end

  # POST /marcas
  # POST /marcas.json
  def create
    @marca = Marca.new(marca_params)

    respond_to do |format|
      if @marca.save
        format.html { redirect_to @marca, notice: 'Marca was successfully created.' }
        format.json { render :show, status: :created, location: @marca }
      else
        format.html { render :new }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marcas/1
  # PATCH/PUT /marcas/1.json
  def update
    respond_to do |format|
      if @marca.update(marca_params)
        format.html { redirect_to @marca, notice: 'Marca was successfully updated.' }
        format.json { render :show, status: :ok, location: @marca }
      else
        format.html { render :edit }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    @marca.destroy
    respond_to do |format|
      format.html { redirect_to marcas_url, notice: 'Marca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marca_params
      params.require(:marca).permit(:descrip)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @marca = Marca.all
    @subcategory = SubCategory.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:descripcion, :cantidad, :cod_bar, :precio_costo, :precio_venta, :sub_category_id, :marca_id)
    end
end

app/controllers/sucursals_controller.rb
class SucursalsController < ApplicationController
  before_action :set_sucursal, only: [:show, :edit, :update, :destroy]

  # GET /sucursals
  # GET /sucursals.json
  def index
    @sucursals = Sucursal.all
  end

  # GET /sucursals/1
  # GET /sucursals/1.json
  def show
  end

  # GET /sucursals/new
  def new
    @sucursal = Sucursal.new
  end

  # GET /sucursals/1/edit
  def edit
  end

  # POST /sucursals
  # POST /sucursals.json
  def create
    @sucursal = Sucursal.new(sucursal_params)

    respond_to do |format|
      if @sucursal.save
        format.html { redirect_to @sucursal, notice: 'Sucursal se guardo con exito.' }
        format.json { render :show, status: :created, location: @sucursal }
      else
        format.html { render :new }
        format.json { render json: @sucursal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sucursals/1
  # PATCH/PUT /sucursals/1.json
  def update
    respond_to do |format|
      if @sucursal.update(sucursal_params)
        format.html { redirect_to @sucursal, notice: 'Sucursal se actualizo con exito.' }
        format.json { render :show, status: :ok, location: @sucursal }
      else
        format.html { render :edit }
        format.json { render json: @sucursal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sucursals/1
  # DELETE /sucursals/1.json
  def destroy
    @sucursal.destroy
    respond_to do |format|
      format.html { redirect_to sucursals_url, notice: 'Sucursal se elimino con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sucursal
      @sucursal = Sucursal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sucursal_params
      params.require(:sucursal).permit(:nombre, :direccion, :localidad, :telefono, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/marca_proveedors_helper.rb
module MarcaProveedorsHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/proveedores_helper.rb
module ProveedoresHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyecto</title>
 <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>


  <header class="header">  


      <nav class="navbar navbar-expand-lg">
<!--
        <div class="search-panel">Buscar
          <div class="search-inner d-flex align-items-center justify-content-center">
            <div class="close-btn">Close <i class="fa fa-close"></i></div>
            <form id="searchForm" action="#">
              <div class="form-group">
                <input type="search" name="search" placeholder="What are you searching for...">
                <button type="submit" class="submit">Search</button>
              </div>
            </form>
          </div>
        </div>
-->


        <div class="container-fluid d-flex align-items-center justify-content-between">
          <div class="navbar-header"><a href="index.html" class="navbar-brand">
              <div class="brand-text brand-big visible text-uppercase"><strong class="text-primary">Tercero </strong><strong>Analisis</strong></div>
              <div class="brand-text brand-sm"><strong class="text-primary">T</strong><strong>A</strong></div></a>
            <button class="sidebar-toggle"><i class="fa fa-long-arrow-left"></i></button>
          </div>
          <ul class="right-menu list-inline no-margin-bottom">    
            <li class="list-inline-item"><a href="#" class="search-open nav-link"><!--<i class="icon-magnifying-glass-browser"></i>--></a></li>


            

           


            <li class="list-inline-item logout"><a id="logout" href="login.html" class="nav-link">Cerrar sesion <i class="icon-logout"></i></a></li>



          </ul>
        </div>
      </nav>
    </header>


    <div class="d-flex align-items-stretch">

      <nav id="sidebar">
        <div class="sidebar-header d-flex align-items-center">
          <div class="avatar"><img src="http://localhost:3000/images/usuario.jpg" alt="..." class="img-fluid rounded-circle"></div>
          <div class="title">
            <h1 class="h5">Tercero Analisis</h1>
            <p>Web Designers</p>
          </div>
        </div><span class="heading">Main</span>
        <ul class="list-unstyled">
          <li class="active"><!--<i class="icon-home"></i>--><%= link_to 'Inicio', 'inicio/index' %></li>
          <li><a href="#dashvariants" aria-expanded="false" data-toggle="collapse"> Proveedores </a>
            <ul id="dashvariants" class="collapse list-unstyled">
              <li ><%= link_to 'Proveedores', proveedores_path %></li>
              <li ><%= link_to 'Marcas', marcas_path %></li>
            </ul>
          </li>

          <li><a href="#prod" aria-expanded="false" data-toggle="collapse"> Productos </a>
            <ul id="prod" class="collapse list-unstyled">
              <li ><%= link_to 'Productos', products_path %></li>
              <li ><%= link_to 'Categorias', categories_path %></li>
              <li ><%= link_to 'Sub categorias', sub_categories_path %></li>
            </ul>
          </li>

          <li>  <!--<i class="icon-grid"></i>--><%= link_to 'Sucursales', sucursals_path %></li>
          <li> <a href="charts.html"> <i class="fa fa-bar-chart"></i>Charts </a></li>
          <li> <a href="forms.html"> <i class="icon-padnote"></i>Forms </a></li>
          <li> <a href="login.html"> <i class="icon-logout"></i>Login Page</a></li>
        </ul><span class="heading">Extras</span>
        <ul class="list-unstyled">
          <li> <a href="#"> <i class="icon-settings"></i>Demo </a></li>
          <li> <a href="#"> <i class="icon-writing-whiteboard"></i>Demo </a></li>
          <li> <a href="#"> <i class="icon-light-bulb"></i>Demo </a></li>
          <li> <a href="#"> <i class="icon-chart"></i>Demo </a></li>
        </ul>
      </nav>



      <div class="page-content">
        <!--
        <div class="page-header">
          <div class="container-fluid">
            <h2 class="h5 no-margin-bottom">Dashboard</h2>
          </div>
        </div>-->



      

<section>
<div class="public-user-block block">
              <div class="row d-flex align-items-center">                   
                <p class="notice"> <%= notice %></p>
                <p class="alert"> <%= alert %></p>
                
                                      <%= yield %>

              </div>
            </div>
</section>

                

        
        

        <footer class="footer">
          <div class="footer__block block no-margin-bottom">
            <div class="container-fluid text-center">
              <!-- Please do not remove the backlink to us unless you support us at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
              <p class="no-margin-bottom">2017 &copy; Tercero analisis</p>
            </div>
          </div>
        </footer>

      </div>
    </div>
    <!-- Javascript files-->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"> </script>
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="vendor/chart.js/Chart.min.js"></script>
    <script src="javascripts/charts-home.js"></script>
    <script src="javascripts/front.js"></script>


 



</body>
</html>